### ISSUE TITLE
Just trying to help you update your blog!

### ISSUE THREAD

**Issue by asciidiego** [vsoch/vsoch.github.io#24]
I saw that you left Stanford for another opportunity.

Congrats on the new position, wishing you all the best!

Are you interested in updating this link?

https://github.com/vsoch/vsoch.github.io/blob/8724999f13bc9a4bae6f2048ff34fe801cb2ee85/_includes/footer.html#L6

**Comment by vsoch** [comment]
Good catch! I totally forgot it was there :laughing: 

I removed the entire thing for now, because more white space is usually better :)

https://github.com/vsoch/vsoch.github.io/commit/f18f6aaffaddc358d452d696c24c25379dab40f5

Thank you!
